### ISSUE TITLE
Database disk image is malformed

### ISSUE THREAD

**Issue by quolpr** [jlongster/absurd-sql#30]
I use Microsoft edge(chrome-based browser), and it supports the Atomics & SharedBuffer, and sometimes I get `database disk image is malformed` error. However, I didn't check if it happens when multiple tabs are opened, and I am unsure under which conditions it is happening.

Here is screenshot from sentry:

![image](https://user-images.githubusercontent.com/7958527/134211940-648102a0-d2b2-46d3-815e-532a6b3e4d31.png)

The stack trace:

```
Error: database disk image is malformed
  at n.handleError(/assets/VaultDb.worker.d94830ba.js:15:55024)
  at e.step(/assets/VaultDb.worker.d94830ba.js:15:50388)
  at n.exec(/assets/VaultDb.worker.d94830ba.js:15:53846)
  at Ri.sqlExec(/assets/VaultDb.worker.d94830ba.js:15:148562)
  at Ri.getRecords(/assets/VaultDb.worker.d94830ba.js:15:148929)
  at Qo.getLinksOfNoteId(/assets/VaultDb.worker.d94830ba.js:15:127812)
  at MessagePort.n(/assets/VaultDb.worker.d94830ba.js:1:1863)
```

**Comment by quolpr** [comment]
The curious thing — after page refresh, the DB is ok and I can access to read and write

**Comment by rshigg** [comment]
I also test on Edge and I've noticed that the database doesn't persist on reload and keeps throwing the same error after the initial write. After refreshing the error goes away but the initial query to get all the rows in the table returns an empty array. I'll add a screenshot of the error soon but I don't think it's an image malformed error. 

I'll try to write some example code to hopefully make it easy to reproduce.

**Comment by quolpr** [comment]
@rshigg I think your issue is not connected with this. I had the same error, and here is the solution https://github.com/jlongster/absurd-sql/issues/14#issuecomment-902116794 . You need to set up the correct CORS

**Comment by rshigg** [comment]
@quolpr thanks for the heads up, that was exactly it! If I come across this issue I'll update here :)

**Comment by cathykc** [comment]
@quolpr Getting the same error intermittently - I'm 85% sure it's when we're doing large reads. Wondering if you found a solution for this. Refreshes also fix the error for us!

@jlongster First of all thanks for this library - it's been a huge lifesaver :) The queries that we're running are pretty simple selects (screenshot below). We have a debug mode that logs the query that's running and results returning. Do you have any advice on what else we could log (and where) to track this issue down? 

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/5464875/155771705-21248fe6-8fbe-46c9-b824-0fcefbda349f.png">

**Comment by steida** [comment]
@cathykc How many tabs did you have? I encountered this error only with two or more tabs.

**Comment by cathykc** [comment]
We had two tabs open!

**Comment by quolpr** [comment]
Ok, I found, at least when it happens — when IndexedDB is resizing. So, if you put 100,000 records in db, and then delete them — this error will never happen till more than 100,000 records will be created again (so absurd-sql will need to create new block in IndexedDB)

**Comment by rhashimoto** [comment]
I was describing alternatives to the Web Locks API to someone, and when I got to the absurd-sql approach I happened on something suspicious that seems worth investigating as a cause for this bug. It's in `Transaction.upgradeExclusive()` which upgrades the lock from SHARED to RESERVED/EXCLUSIVE:

https://github.com/jlongster/absurd-sql/blob/ade37d94c78d0156da73e7bd540696b39269d9e6/src/indexeddb/worker.js#L95-L111

This method abandons its read lock by discarding the existing "readonly" IDBTransaction and attempts the upgrade by creating a new "readwrite" IDBTransaction. It then checks that no other connection modified the database in between those operations by verifying that certain bytes in the first block are unchanged.

Let's assume that some other connection did in fact modify the database and that first block is different. What happens?

The VFS is going to return a status code that it failed to obtain the lock. But what state is it leaving behind? The Transaction instance is going to have `LOCK_TYPE.EXCLUSIVE` set, it will contain a "readwrite" IDBTransaction, and It has cached the new first block data. Meanwhile, SQLite thinks the lock state is still SHARED (because the upgrade failed) and it still has the original first block data in its cache. These discrepancies make me very nervous.

For one thing, the SQLite locking model is now broken. As far as SQLite knows, it is still in SHARED mode and can continue to read from the database. But the IDBTransaction it was using to read (and counting on for consistency) is now gone. If SQLite does happen to make calls that go to a new IDBTransaction, eventually it will get very confused.

For another thing, if that Transaction instance state isn't reset and remains active, then the next attempt the to upgrade the lock will succeed (because it thinks it is already in the upgraded state). I don't know if this retry actually happens, but if it does then that opens the door to corruption.

Now whether or not this is in fact the cause of this bug, I don't think this upgrade approach of dropping read-only, acquiring read-write, and checking for changes can be made to work with the SQLite locking model because I don't think you can preserve the SHARED lock. There is no way to tell SQLite that not only did it not upgrade the lock, it also lost its original lock.

Anyway, I'm just posting this in case it's helpful to someone. I don't plan on pursuing it further myself.

**Comment by quolpr** [comment]
@rhashimoto good discover 👍

**Comment by midwesterntechnology** [comment]
Getting this too. Used to happen occasionally but would be fixed by a refresh. Lately though, it seems to permanently corrupt the database in question (can't open it ever again without getting the error - have to delete the IDB database and make a new one). Only happens with multiple tabs.

**Comment by mrmurphy** [comment]
We just ran into this with our pre-release product. While one tab is doing a lot of writes, the other can read just fine. But if the other tab attempts a write as well we get a warning that the disk image is malformed.
