### ISSUE TITLE
Export DB throw error.

### ISSUE THREAD

**Issue by portguas** [jlongster/absurd-sql#75]
I'm using absurd-sql in electron.
I export the db like this.
```
try {
      const db = await getInstance()
      const data = db.export()
      const blob = new Blob([data], { type: 'application/octet-stream' })
      const blobHref = URL.createObjectURL(blob)

      self.postMessage({ action: 'exportedDB', blobHref })
    } catch (error) {
      console.info('sql export error, return ', error)
    }
```
It got error.
```
sql export error, return  TypeError: Cannot read properties of undefined (reading 'constructor')
    at readChunks (indexeddb-backend.js:65:20)
    at File.read (indexeddb-backend.js:248:22)
    at Object.read (index.js:101:37)
    at Object.read (sql-wasm.js:151:211)
    at Object.readFile (sql-wasm.js:154:349)
    at c.export (sql-wasm.js:88:238)
    at self.onmessage (instance.ts?type=mod…er_file? [sm]:86:23)
 ```
 The error caused by  _const data = db.export()_
 In indexeddb-backend.js ，the data in undefined.
 ```
 if (chunk.data.constructor.name !== 'ArrayBuffer') {
      throw new Error('Chunk data is not an ArrayBuffer');
    }
 ```
How can i resolve it. Thanks.

**Comment by kkosteck** [comment]
This workaround worked for me  - instead of using `db.export()` I used direct `readFile` function:
```js
import SQLWasm from '@jlongster/sql.js/dist/sql-wasm-debug.wasm?url'
const DATABASE_NAME = 'db.sqlite'
SQL = await initSqlJs({ locateFile: () => SQLWasm })
let sqlFS = new SQLiteFS(SQL.FS, new IndexedDBBackend())
SQL.register_for_idb(sqlFS)

SQL.FS.mkdir('/sql')
SQL.FS.mount(sqlFS, {}, '/sql')

// I had to use 'a+' flag here, because using 'r' throws error
const data = SQL.FS.readFile(`/sql/${DATABASE_NAME}`, { encoding: 'binary', flags: 'a+' })
```
